[project]
name = "mcp-client-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.21.0",
    "rich>=14.2.0",
]
